// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	EventType            string          `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Ts                   int64           `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Params               *_struct.Struct `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Event) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Event) GetParams() *_struct.Struct {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "timeseries.api.v1.event")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0xcb, 0x2e, 0x74, 0x5c, 0x04, 0x73, 0xd0, 0x52, 0x15, 0xca, 0x9e, 0x7a, 0x4a,
	0x71, 0x7d, 0x01, 0x11, 0xf7, 0x05, 0x1a, 0x4f, 0x5e, 0x24, 0xbb, 0x8c, 0x25, 0x60, 0x4c, 0x48,
	0x66, 0x0b, 0x7d, 0x11, 0x9f, 0x57, 0x3a, 0xd5, 0x8b, 0xbd, 0x79, 0x1b, 0xfe, 0xff, 0xe7, 0xfb,
	0x18, 0x28, 0x4c, 0xb0, 0x2a, 0x44, 0x4f, 0x5e, 0x5e, 0x92, 0x75, 0x98, 0x30, 0x5a, 0x4c, 0x6a,
	0x4a, 0x87, 0xfb, 0xea, 0xa6, 0xf7, 0xbe, 0xff, 0xc0, 0x96, 0x07, 0x87, 0xd3, 0x7b, 0x8b, 0x2e,
	0xd0, 0x38, 0xef, 0xab, 0xdb, 0xbf, 0x65, 0xa2, 0x78, 0x3a, 0xd2, 0xdc, 0x6e, 0x7b, 0x58, 0xe1,
	0x80, 0x9f, 0x24, 0xef, 0x00, 0xf8, 0x78, 0xa3, 0x31, 0x60, 0x29, 0x6a, 0xd1, 0x14, 0x5d, 0xc1,
	0xc9, 0xcb, 0x18, 0x50, 0x5e, 0x40, 0x46, 0xa9, 0xcc, 0x6a, 0xd1, 0xe4, 0x5d, 0x46, 0x49, 0xb6,
	0xb0, 0x0e, 0x26, 0x1a, 0x97, 0xca, 0xbc, 0x16, 0xcd, 0xf9, 0xee, 0x5a, 0xcd, 0x1a, 0xf5, 0xab,
	0x51, 0x9a, 0x35, 0xdd, 0xcf, 0x6c, 0xf7, 0x25, 0x60, 0xb3, 0x9f, 0x70, 0x1a, 0xe3, 0x60, 0x8f,
	0x28, 0x1f, 0x01, 0x34, 0xf9, 0x88, 0x1c, 0xca, 0x52, 0x2d, 0xde, 0x52, 0x6c, 0xaf, 0xae, 0x16,
	0xe4, 0xfd, 0xf4, 0xdd, 0xf6, 0x4c, 0x3e, 0xc3, 0x46, 0x53, 0x44, 0xe3, 0x18, 0x91, 0xfe, 0xc3,
	0x68, 0xc4, 0xd3, 0xea, 0x35, 0x37, 0xc1, 0x1e, 0xd6, 0x5c, 0x3d, 0x7c, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x33, 0x0f, 0x14, 0xf5, 0x6a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	StoreEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*empty.Empty, error)
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (EventService_StreamEventsClient, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) StoreEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/timeseries.api.v1.EventService/StoreEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (EventService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventService_serviceDesc.Streams[0], "/timeseries.api.v1.EventService/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventServiceStreamEventsClient{stream}
	return x, nil
}

type EventService_StreamEventsClient interface {
	Send(*Event) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type eventServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *eventServiceStreamEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventServiceStreamEventsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	StoreEvent(context.Context, *Event) (*empty.Empty, error)
	StreamEvents(EventService_StreamEventsServer) error
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_StoreEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).StoreEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timeseries.api.v1.EventService/StoreEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).StoreEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventServiceServer).StreamEvents(&eventServiceStreamEventsServer{stream})
}

type EventService_StreamEventsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type eventServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *eventServiceStreamEventsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventServiceStreamEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timeseries.api.v1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreEvent",
			Handler:    _EventService_StoreEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventService_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}
